name: agrocart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  google_sign_in: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/image/content/
    - assets/image/banners/
    - assets/image/reviews/
    - assets/image/products/
    - assets/image/products/cattle/
    - assets/icons/categories/
    - assets/image/animations/
    - assets/icons/payment_methods/
    - assets/image/on_boarding_images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Bangla
      fonts:
        - asset: assets/fonts/boldbangla.ttf
          weight: 800
        - asset: assets/fonts/regularbangla.ttf
          weight: 400
        - asset: assets/fonts/semiboldbangla.ttf
          weight: 600
