// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4q0k38rBaUCa6XkMo8Vv1NseF6KXXp4',
    appId: '1:834736555405:web:456d144ddfb580ccade9c4',
    messagingSenderId: '834736555405',
    projectId: 'agrocart-8fcae',
    authDomain: 'agrocart-8fcae.firebaseapp.com',
    storageBucket: 'agrocart-8fcae.firebasestorage.app',
    measurementId: 'G-H4RDCHPH2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPVtaCKls5WUujMjLJ_HY6j6UyunFj1w',
    appId: '1:834736555405:android:54dcfa4537fb5255ade9c4',
    messagingSenderId: '834736555405',
    projectId: 'agrocart-8fcae',
    storageBucket: 'agrocart-8fcae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PRNrX7FLhVyD8JZmGZa_ty8zOF5Lm6o',
    appId: '1:834736555405:ios:10e1c8e50112a888ade9c4',
    messagingSenderId: '834736555405',
    projectId: 'agrocart-8fcae',
    storageBucket: 'agrocart-8fcae.firebasestorage.app',
    iosBundleId: 'com.example.agrocart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2PRNrX7FLhVyD8JZmGZa_ty8zOF5Lm6o',
    appId: '1:834736555405:ios:10e1c8e50112a888ade9c4',
    messagingSenderId: '834736555405',
    projectId: 'agrocart-8fcae',
    storageBucket: 'agrocart-8fcae.firebasestorage.app',
    iosBundleId: 'com.example.agrocart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4q0k38rBaUCa6XkMo8Vv1NseF6KXXp4',
    appId: '1:834736555405:web:f38faf90616b7479ade9c4',
    messagingSenderId: '834736555405',
    projectId: 'agrocart-8fcae',
    authDomain: 'agrocart-8fcae.firebaseapp.com',
    storageBucket: 'agrocart-8fcae.firebasestorage.app',
    measurementId: 'G-VPLL80T58W',
  );
}
